### ISSUE TITLE
deepMerge exception when trying to merge object onto null

### ISSUE THREAD

**Issue by mackermedia** [herrstucki/sprout#8]
```
var item1 = { foo: { bar: null }}
var item2 = { foo: { bar: { id: 1 }}}

deepMerge(item1, item2)
```

Results in:
![](https://s3.amazonaws.com/vigesharing-is-vigecaring/mackerman/deepMerge_bug_2017-02-24_16-55-14.png.png)

**Comment by herrstucki** [comment]
Thanks for the request. Unfortunately, I don't really have time to maintain this module at the moment, and I don't use it myself anymore. So if you'd be interested to maintain it further, I'd be happy to hand it over 😄
